# Generated by Django 6.0.3 on 2026-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_team_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='last_generation',
            field=models.JSONField(blank=True, default=None, help_text='Raw AI generation output for audit (model, tokens, raw tasks, timestamp)', null=True),
        ),
    ]
