# Generated by Django 6.0.2 on 2026-02-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('mention', 'Mention'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed'), ('deadline_warning', 'Deadline Warning'), ('summary_ready', 'Summary Ready')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task'),
        ),
    ]
