import logging
import re

from apps.telegram.services import send_telegram_message, verify_code_and_link

logger = logging.getLogger(__name__)

# Matches base64url tokens (the format generated by secrets.token_urlsafe)
_CODE_PATTERN = re.compile(r"^[A-Za-z0-9_-]{20,64}$")


def _try_verify(code, chat_id, telegram_username):
    """Attempt to verify a code and send a response message."""
    success, error = verify_code_and_link(code, chat_id, telegram_username)
    if success:
        send_telegram_message(
            chat_id,
            "Account linked! You will now receive task notifications here.",
        )
        logger.info("Telegram account linked for chat_id=%s", chat_id)
    else:
        send_telegram_message(chat_id, f"Linking failed: {error}")
        logger.warning("Telegram linking failed for chat_id=%s: %s", chat_id, error)


def handle_webhook_update(payload):
    """Parse a Telegram Update JSON and handle /start commands."""
    message = payload.get("message")
    if not message:
        return

    text = message.get("text", "")
    chat = message.get("chat", {})
    chat_id = chat.get("id")
    from_user = message.get("from", {})
    telegram_username = from_user.get("username", "")

    if not chat_id:
        return

    # Handle /start <code> deep link
    if text.startswith("/start "):
        code = text[7:].strip()
        if not code:
            send_telegram_message(chat_id, "Please use the link from the settings page.")
            return
        _try_verify(code, chat_id, telegram_username)

    elif text == "/start":
        send_telegram_message(
            chat_id,
            "Welcome! To link your account, use the link from your settings page.\n\n"
            "If the link didn't work automatically, copy the verification code "
            "from the settings page and paste it here.",
        )

    # Handle /verify <code> as explicit fallback command
    elif text.startswith("/verify "):
        code = text[8:].strip()
        if not code:
            send_telegram_message(chat_id, "Usage: /verify <code>")
            return
        _try_verify(code, chat_id, telegram_username)

    # Handle plain text that looks like a verification code
    elif _CODE_PATTERN.match(text.strip()):
        _try_verify(text.strip(), chat_id, telegram_username)
