# Generated by Django 5.0.14 on 2026-01-31 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='created', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='tags.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ix_task_status'), models.Index(fields=['priority'], name='ix_task_priority'), models.Index(fields=['deadline'], name='ix_task_deadline'), models.Index(fields=['created_at'], name='ix_task_created_at'), models.Index(fields=['status', 'priority'], name='ix_task_status_priority'), models.Index(fields=['status', 'deadline'], name='ix_task_status_deadline')],
            },
        ),
    ]
