# Generated by Django 6.0.3 on 2026-04-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_deadline_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='AI or manual time estimate in hours', max_digits=6, null=True),
        ),
    ]
