# Generated by Django 6.0.2 on 2026-02-13 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('on_demand', 'On-demand')], db_index=True, max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('generation_method', models.CharField(blank=True, choices=[('ai', 'AI'), ('fallback', 'Fallback template')], default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Summary',
                'verbose_name_plural': 'Report Summaries',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['period_type', 'period_start', 'period_end'], name='idx_summary_period'), models.Index(fields=['period_type', 'period_start', 'period_end', '-generated_at'], name='idx_summary_period_latest')],
            },
        ),
    ]
