# Generated by Django 6.0.3 on 2026-04-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_summaries', '0004_add_prompt_text_and_sections'),
        ('clients', '0004_enforce_organization_notnull'),
        ('projects', '0003_add_last_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummary',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='clients.client'),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='focus_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='projects.project'),
        ),
    ]
