# Generated by Django 5.0.14 on 2026-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('color', models.CharField(blank=True, default='#6c757d', max_length=7)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='ix_tag_slug')],
            },
        ),
    ]
