# Generated by Django 6.0.3 on 2026-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_verbose_names'),
        ('tags', '0003_enforce_organization_notnull'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='ix_tag_slug',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'organization')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
