# Generated by Django 6.0.3 on 2026-04-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_summaries', '0006_add_llm_model'),
        ('organizations', '0003_alter_organization_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_llm_model',
            field=models.ForeignKey(blank=True, help_text="Default LLM model for this organization's AI generations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='ai_summaries.llmmodel', verbose_name='default LLM model'),
        ),
    ]
